language: python
python:
  - "2.7"
install: # command to install dependencies
  - "pip install -r requirements.txt"
# command to run tests
script: python test.py

notifications:
  email:
       jamesleahy314@gmail.com

sudo: false
